### ISSUE TITLE
TypeError: Cannot read property 'name' of null (eventData.pull_request.head.repo.name)

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster-github#105]
https://sentry.io/taskcluster/taskcluster-github/issues/208036664/

```
TypeError: Cannot read property 'name' of null
  File "/app/lib/api.js", line 46, in getPullRequestDetails
    'event.head.repo.name': eventData.pull_request.head.repo.name,
  File "/app/lib/api.js", line 223, in Object._callee$
    msg.details = getPullRequestDetails(body);
  File "/app/lib/api.js", line 303, in Object.<anonymous>
    return _ref.apply(this, arguments);
...
(11 additional frame(s) were not displayed)

TypeError: Cannot read property 'name' of null
```

**Comment by imbstack** [comment]
This has only happened once so far, so I won't roll it back yet. https://sentry.io/taskcluster/taskcluster-github/issues/208036664/#extra contains the webhook contents itself and indeed `pull_request.head.repo` is null :/

**Comment by imbstack** [comment]
That PR was https://github.com/mozilla/pontoon/pull/534 which isn't configured to use tc at all anyway, so we haven't impacted anybody.

**Comment by imbstack** [comment]
This event appears to be for the pull request being closed afaict. Perhaps that does not have `pull_request.head.repo` defined? It appears to in the examples on https://developer.github.com/v3/activity/events/types/#pullrequestevent but in that example the `closed_at` is `null`. I'm thinking we should grab this `name` info from the top-level `repository` field that appears to come with events, rather than `pull_request.head`? I'm going to look into this a bit more and see if that is supposed to always come with the events.

**Comment by imbstack** [comment]
We now grab this from `sender.login`. I believe this should be resolved.

**Comment by djmitche** [comment]
https://github.com/mozilla-bteam/bmo/pull/32 has no head repository (`unknown repository`).  I'm guessing the repo was deleted?  So, we should probably handle this.
