### ISSUE TITLE
Responding to pull request changes sometimes takes a long time (better monitoring)

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster-github#107]
This is something I've only noticed in the past week or so - sometimes it takes upwards of 5 minutes for Taskcluster to notice a change to a pull request. For example, on https://github.com/mozilla/balrog/pull/211,  9f9980a  was added at 11:35am eastern, but the Tasks were not created until 11:40.

This isn't the end of the world, but it's unfortunate that nothing about the PR is updated for that long.

**Comment by imbstack** [comment]
https://api.github.com/repos/mozilla/balrog/statuses/9f9980a shows all of the statuses for this sha. We can see from that that we've run 4 different times for 4 events. In order of creation time: [pull_request.synchronize](https://tools.taskcluster.net/task-group-inspector/#/Ipavb_iaRUKXKQgQJnH9rw/KM-Sr4V7Rmml1VmZH6SAmQ?_k=0rgxoe), [pull_request.assigned](https://tools.taskcluster.net/task-group-inspector/#/Pfp_teLuRZa3Pqof5-hMNQ/XagNroyCTxGd5nLmpqO_1g?_k=7mkvc5), [pull_request.unassigned](https://tools.taskcluster.net/task-group-inspector/#/aIhxaxsnSfmPOPn-UvA1yA/BpOLJIF0QRyxZ7Kmiag4Tw?_k=xg625r), [pull_request.closed](https://tools.taskcluster.net/task-group-inspector/#/fmhWZeHTTEmtSFKcCxx70g/IJNBQUD0QdeDFBt-V-S01w?_k=zbk0oz). However, none of those were created before 11:40, which was already too late (Do we want to be running these tests 4 times though? I suppose that's a question for another time).

[A one month handler timing](https://app.signalfx.com/#/dashboard/CjP26bHAcAM?startTime=-31d&endTime=Now) doesn't show any generic slowdown that I can see in the speed of the handler. Even a [zoomed in view](https://app.signalfx.com/#/chart/v1/CjP4vmZAYAQ?startTimeUTC=1485448115000&endTimeUTC=1485448822000) on the event itself shows the handler still finishing in ~100ms. This leads me to believe that the delay is in one of two places:

1. In pulse between the api receiving the webhook and the handler working on the webhook
2. In github between the event happening and the webhook being fired.

I have a hunch it is option 1. I'll look into this a bit more.

**Comment by imbstack** [comment]
I have the logs from the webhook and they seem to match up to the logs of the api in tc-gh w.r.t. timing, so at the moment my best guess is some sort of pulse weirdness. I'm going to add more logging and monitoring around this. Please let me know if you notice this again and hopefully we'll be able to figure out more about it then.

**Comment by bhearsum** [comment]
Thanks for looking into this. It seems faster today, for what it's worth. I'll let you know if it slows down again though.

**Comment by djmitche** [comment]
I have convinced @imbstack that we should keep the pulse messages beteween webhooks and the handlers.  However, we should have some monitoring of the time delta between an event, the webhook, and the handler execution.

In fact, we may be seeing a delay here due to failure.

**Comment by imbstack** [comment]
Tracking this in [bug 1441960](https://bugzilla.mozilla.org/show_bug.cgi?id=1441960)
