### ISSUE TITLE
Path changes needed

### ISSUE THREAD

**Issue by hwine** [taskcluster/taskcluster-github#207]
GitHub is changing URLs associated with GitHub apps (nee integrations). Details and timetable in the [blog post](https://developer.github.com/changes/2017-07-19-removal-of-integrations-routes/)

**Comment by imbstack** [comment]
Thanks for the heads up. I'll search for our usages of this now!

**Comment by notriddle** [comment]
In this repo's description, at the top of the main page, it says "Integrate Taskcluster with Github. https://github.com/integration/taskcluster"

**Comment by notriddle** [comment]
Somebody with permission should probably change that to https://github.com/apps/taskcluster

**Comment by imbstack** [comment]
Hah, I missed that one in my grepping. Fixed!

**Comment by notriddle** [comment]
Grep's not going to find that kind of thing.
