### ISSUE TITLE
Badges have turned into empty space

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster-github#231]
Badges such as [this one](https://github.taskcluster.net/v1/repository/mozilla/DeepSpeech/master/badge.svg) are now just showing up as empty black images with the correct border. Not sure what changed unfortunately.

**Comment by ccooper** [comment]
If I try to load https://github.taskcluster.net/v1/repository/mozilla/DeepSpeech/master/badge.svg directly, I see the black image you describe, but the badge displays properly in situ: https://github.com/mozilla/DeepSpeech/blob/master/README.md

WORKSFORME?

**Comment by djmitche** [comment]
I saw this in a README (I think on npmjs?) just the other day.  I wonder if there's some subtle thing wrong with that SVG that occasionally triggers a render error in Firefox?  At any rate, not WORKSFORME I think..

**Comment by imbstack** [comment]
WORKSFORME works for me as well.
