### ISSUE TITLE
Reruns don't change status check result

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster-github#235]
Sometimes we end up with infrastructure failures as part of PR checks. These are usually fixable by rerunning the Task, but doing so doesn't change the status on Github. For example, https://github.com/mozilla/balrog/pull/515 had one failing Task (https://tools.taskcluster.net/groups/RxbsRtsYTmu_PeOQK58DHQ/tasks/RxbsRtsYTmu_PeOQK58DHQ/runs/0), which I reran. The Task (and Group) are green now, but the status check is still showing a failure. (For posterity, here's a screenshot of both: https://hearsum.ca/~bhearsum/2ad3488b.png)

This is particularly inconvenient when Taskcluster is a required status check -- patches cannot be merged without changing something on the branch to get an entirely new commit + CI.

**Comment by garbas** [comment]
:+1: confirming this issue. it would be nice that status check would be updated after successful reruns

**Comment by bhearsum** [comment]
There seems to have been a rise in intermittent failures in recent weeks, which is making this a bit more annoying - I have at least a few PRs a week that end up with "failures" even though reruns are fine.

**Comment by imbstack** [comment]
Yeah, this is definitely frustrating. The tc-github team is pretty heads-down in some other projects right at this moment, but maybe soon we can find some time to figure something out with this. It's not as straightforward as one might hope. I can give some guidance to someone who has time to hack on this though! Should be a couple days of work at most.

**Comment by imbstack** [comment]
Continuing in https://bugzilla.mozilla.org/show_bug.cgi?id=1465161
