### ISSUE TITLE
Permission denied in ubuntu-ci image

### ISSUE THREAD

**Issue by rail** [taskcluster/taskcluster-github#26]
See https://tools.taskcluster.net/task-graph-inspector/#CxZTDmkKTzSxPjrWumSbJA/I1JH2PSIT5if58ZCi1vkTQ/0

It's related to https://github.com/docker/docker/issues/783

I hit this issue on my local machine yesterday using docker 1.8.2 and aufs. Switching to overlayfs or btrfs fixed the issue. Interestingly, I cannot reproduce it, when build the image locally.

**Comment by djmitche** [comment]
We've upgraded to Docker 1.16 or somewhere around there -- perhaps that fixes it?  This is an old issue, so I'm going to close in hopes that's the case :)

**Comment by djmitche** [comment]
We've also deprecated that image (it has a LOT of security vulns in it, since it's ancient)
