### ISSUE TITLE
checkout-pull-request should exit non zero if it fails to clone

### ISSUE THREAD

**Issue by rail** [taskcluster/taskcluster-github#27]
See https://tools.taskcluster.net/task-graph-inspector/#CxZTDmkKTzSxPjrWumSbJA/I1JH2PSIT5if58ZCi1vkTQ/0

There are actually 2 issues here:
1) $GITHUB_HEAD_BRANCH is not set, but checkout-pull-request requires it.
2) it fails to checkout but exits 0, what makes the build green.

**Comment by djmitche** [comment]
We're deprecating support for the custom docker image with the checkout-pull-request script in it, preferring instead to embed those commands in `.taskcluster.yml` (it's more readable that way, and allows use of upstream docker images like `node` or `python`).
