### ISSUE TITLE
Docs: .taskcluster.yml v1 example is missing "created" field

### ISSUE THREAD

**Issue by JohanLorenzo** [taskcluster/taskcluster-github#271]
The example provided in https://docs.taskcluster.net/docs/reference/integrations/taskcluster-github/docs/taskcluster-yml-v1 doesn't list the required field `created`. See https://github.com/mozilla-mobile/fenix/pull/64#commitcomment-30478953

**Comment by djmitche** [comment]
Hm, #267 did that intentionally, but it looks like it added `created` to the context, rather than adding it to the task.  @owlishDeveloper can probably take a look :)

**Comment by owlishDeveloper** [comment]
L👀king :)

**Comment by owlishDeveloper** [comment]
What I'm not sure about, however, is why in that PR https://github.com/mozilla-mobile/fenix/pull/64 the `v1` was evaluated against `v0` schema 🤔

**Comment by djmitche** [comment]
Is it possible that we look for the version in the master branch (where we look for the PR policy) instead of in the file itself?

**Comment by owlishDeveloper** [comment]
💯

**Comment by owlishDeveloper** [comment]
Solved
