### ISSUE TITLE
Convert sanitized repository names back to having '.' in them before trying to access them

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster-github#52]
In the endpoint that receives the webhook from github, we [remove certain characters from certain fields](https://github.com/taskcluster/taskcluster-github/blob/master/src/api.js#L11). I'm not sure why this is yet (I'm guessing maybe pulse wants the routing key to have no '.'?) but I don't see where we're converting back inside the worker in order to call out to the github api. I don't think (also not confirmed) that github understands `science%mozilla%org` to mean `science.mozilla.org`. I think this might cause us to not be able to run repositories with '.' in them, but not confirmed quite yet.

**Comment by imbstack** [comment]
After creating a little test case, I'm pretty sure that is what is causing the entire fully-formed huge html documents to show up in the logs.

I expect it's coming from https://github.com/taskcluster/taskcluster-github/blob/master/src/worker.js#L64

**Comment by imbstack** [comment]
This is kinda done now. Now that I understand pulse better, I think I'd be much happier if we did something like the route path munging like we do in [taskcluster-notify](https://github.com/taskcluster/taskcluster-notify/blob/master/src/handler.js#L80).

**Comment by djmitche** [comment]
This seems to work for https://github.com/devtools/debugger.html, so I'm assuming it's good!  Brian thinks so too..
