### ISSUE TITLE
Figure out a way to make bots able to run tc jobs on push/PR

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster-github#56]
Currently when the greenkeeper bot pushes a branch and makes a PR on any of our repositories that are managed that way, [tc-github gives a 403](https://github.com/organizations/taskcluster/settings/hooks/5636704#delivery-response) claiming `Bad Signature`. I have a hunch that this is because tc-github doesn't know that we've allowed greenkeeper to be doing this sort of thing. I need to investigate further, but presumably there's a way we can figure out that the org has given permissions to the bot and therefore allow it to run builds on pushes/PRs.

**Comment by djmitche** [comment]
The core issue here is that the bot is not a collaborator, so this may mean expanding `isCollaborator` to also allow building PRs from integrations.

**Comment by djmitche** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1257540 should address this
