### ISSUE TITLE
request/response should be defined

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster-github#60]
See https://docs.taskcluster.net/reference/core/github/api-docs

The docs need writing, and we need to define request/response schemas, otherwise nobody can integrate with the service.

**Comment by djmitche** [comment]
We're sort of "abusing" taskcluster-lib-app here, as the resulting API has no taskcluster endpoints, and does not enforce schemas (since github provides webhooks with lots of different shapes).

So I don't think there's anything to do here.
