### ISSUE TITLE
commit on PR branch triggers task graph run using original .taskcluster.yml

### ISSUE THREAD

**Issue by mykmelez** [taskcluster/taskcluster-github#72]
Over in https://github.com/mozilla/positron/pull/121, I've been improving Positron's .taskcluster.yml file via a series of incremental changes. And until recently, each time I've pushed a change, TaskCluster has used the new .taskcluster.yml file to configure a task graph run.

But the most recent change, https://github.com/mozilla/positron/pull/121/commits/46799e7206736db0e03b7ce6f6dc9e30fadd5fd7, triggered a task graph run that appears to be using the original, unmodified .taskcluster.yml rather than the one on the branch.

Strangely, the most recent change also triggered two runs:
- https://tools.taskcluster.net/task-graph-inspector/#N-Pj3JQgRQeSu0Nd-xF6PA is referenced by the status "dot" next to the revision ID and the "Details" link.
- https://tools.taskcluster.net/task-graph-inspector/#NFbkLaNiS_CVE01iwpdQrA is referenced by this [TaskClusterRobot comment on the revision](https://github.com/mozilla/positron/pull/121#commitcomment-19104742).

Note: I'm using a branch in the upstream repository (https://github.com/mozilla/positron) rather than one in my fork (https://github.com/mykmelez/positron) because of this "note on testing" on [TaskCluster GitHub](https://docs.taskcluster.net/manual/vcs/github):

> TaskCluster GitHub will not use .taskcluster.yml files from pull requests. To test .taskcluster.yml changes create a new branch on the master/base repository and open pull requests against it or make pushes to it (depending on the events you have enabled).

Based on that note, I would expect TaskCluster to do what it has been doing until the most recent change: use the revised .taskcluster.yml file in the branch, since the branch is on the master/base repository.

**Comment by mykmelez** [comment]
https://github.com/mozilla/positron/pull/121 just got squashed and merged, but the merge run is still using the old .taskcluster.yml file:

https://tools.taskcluster.net/task-graph-inspector/#b5Mrp3D5TZeLJqGeAueyPg

**Comment by mykmelez** [comment]
I ended up merging the .taskcluster.yml changes to the master branch of the repo, which appears to have worked around the problem. But I'm leaving this issue open, since it still seems like a bug in taskcluster-github that it happened.

**Comment by Standard8** [comment]
@imbstack fixed this yesterday by landing 6507044f51ae8f07d9c89829abe019ab19474729, a backout of a73d8f1609f87b1bae95ab0187da55a45ae9e692
