### ISSUE TITLE
taskcluster-github adds browser history item when it rewrites URL to add trailing slash

### ISSUE THREAD

**Issue by mykmelez** [taskcluster/taskcluster-github#73]
The URL that taskcluster-github uses for task-graph-inspector links (f.e. the status icon link and the "Details" link in a pull request) contains no trailing slash, f.e.:

https://tools.taskcluster.net/task-graph-inspector/#Rjr993ErSe6LRpv3O-rS5A

But when you follow that link, the URL gets changed to a version that contains a trailing slash, f.e.:

https://tools.taskcluster.net/task-graph-inspector/#Rjr993ErSe6LRpv3O-rS5A/

Unfortunately, the change happens in a way that adds a history item to the browser's history for the tab. So if you then press the browser "Back" button, you go "back" to the same page, but without the trailing slash on the URL. And you have to press "Back" again to get back to the page you were on before.

If it's necessary to add the slash, it should happen in a way that doesn't add an item to the browser's history.

**Comment by imbstack** [comment]
This should be fixed in the latest update. The links now contain a trailing slash. Thanks for the report! I never noticed this happening before.
