### ISSUE TITLE
win2012r2 workertype doesn't work under tc-gh

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster-github#78]
A PR with https://github.com/mozilla/example-addon-repo/blob/master/.taskcluster.yml#L110 in it was rejected due to a lack of scopes: https://github.com/mozilla/example-addon-repo/pull/37

I'm going to investigate if this was broken by an update to tc-gh or if tc-gh just isn't allowed to assign things to that workertype or if the repo itself needs extra scopes.

@standard8 did this used to work for you or is it a new task?

**Comment by Standard8** [comment]
@imbstack This was working yesterday afternoon BST time for me. So I think this is broken by an update.

We assigned scopes to the repository a while ago to allow it to access the win2012r2 builders:

https://tools.taskcluster.net/auth/roles/#repo:github.com%252fmozilla%252fexample-addon-repo:*

It looks like its now asking for `queue:create-task:aws-provisioner-v1/win2012r2` as well as `queue:define-task:aws-provisioner-v1/win2012r2` ?

**Comment by djmitche** [comment]
done
