### ISSUE TITLE
If the branch contains a slash, then GITHUB_HEAD_BRANCH is set incorrectly.

### ISSUE THREAD

**Issue by Standard8** [taskcluster/taskcluster-github#94]
A PR was created by greenkeeper, on a branch called `greenkeeper/update-all`. The resulting task was:

https://tools.taskcluster.net/task-group-inspector/#/C6HDrZviTcusOfVhqcneFw/KT9QPaemTZqMVevN8Y2-6A?_k=ds29s1

As you can see from the task details, the GITHUB_HEAD_BRANCH variable was set to `greenkeeper` rather than `greenkeeper/update-all`.

**Comment by owlishDeveloper** [comment]
@Standard8 should be good now!

**Comment by djmitche** [comment]
Did someone (@imbstack?) merge this to production?

**Comment by owlishDeveloper** [comment]
It's not in production yet, reopen

**Comment by djmitche** [comment]
Now it is - I just promoted it.  Sorry about that!

**Comment by owlishDeveloper** [comment]
Thank you!

**Comment by Standard8** [comment]
@owlishDeveloper Thanks for fixing this, used it today & it worked fine :-)
