### ISSUE TITLE
Error: {"message": "No server is currently available to service your request. Sorry about that. Please t...

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster-github#96]
Not sure if we should figure out a way to handle this with retries or not. Leaving this for now.

https://sentry.io/taskcluster/taskcluster-github/issues/204412157/

```
Error: {"message": "No server is currently available to service your request. Sorry about that. Please try resubmitting your request and contact us if the problem persists."}

Error: {"message": "No server is currently available to service your request. Sorry about that. Please try resubmitting your request and contact us if the problem persists."}

```

**Comment by djmitche** [comment]
This is an API error from Github.  We should figure out how to handle these appropriately -- maybe by automatically retrying on 5xx errors (it's a 503).

**Comment by ydidwania** [comment]
Hi, I would like to work on this bug. I am unable to view the error link . How should I proceed?

**Comment by imbstack** [comment]
Hi @ydidwania, this might not be the most interesting bug to work on. The link also goes to a place that we no longer have access to either so it is lost to the sands of time. Ping me/dustin in irc and we can figure out a more fun bug to work on!

**Comment by ydidwania** [comment]
Okay, thanks @imbstack
