### ISSUE TITLE
badly formatted .taskcluster.yml should be handled

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster-github#98]
Currently, we'll get a warning in papertrail, like:

```
 Tue, 17 Jan 2017 18:09:46 GMT taskcluster-github error (reported to sentry) while calling job handler: YAMLException: bad indentation of a sequence entry at line 83, column 39: 
```

Instead we should probably post a message to PR / commit to say that the `.taskcluster.yml` is malformed, and mark it as a failure. Currently, you just don't get a message e.g. in the PR so you don't know if the format was bad, or if the service is down.

CC: @owlishDeveloper @imbstack @djmitche

**Comment by djmitche** [comment]
dup of https://bugzilla.mozilla.org/show_bug.cgi?id=1330177

I don't know if it makes sense to split tc-github tracking between github issues and bugzilla.. but no sense having the same thing in two places..
