### ISSUE TITLE
Intermittent: some token substitutions not working in a pull request

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster-github#99]
Compare these two tasks, generated from the same PR:

1) https://queue.taskcluster.net/v1/task/ERiMtxoYSri-M0YWhMzBSA
2) https://queue.taskcluster.net/v1/task/ICyhFSvWTFWYJfmTi15pKA

The tokens in the first task have been properly substituted, such that we have a valid task. The second task still contains the literal text `{{ event.base.user.login }}`.

The missing substitutions seem to be intermittent and happened about one time in six for me (at a guess).

I noticed that `{{ event.base.user.login }}` is a token which is replaced for a pull request, but not replaced for a push, so I wonder if there is a race condition, such that when a commit is pushed to a branch where there is an active pull request, sometimes the push event might win the race against the pull request event, and then the task is generated as if it was for a regular push rather than for a pull request. This is based on looking at the data in https://github.com/taskcluster/taskcluster-github/blob/912b765f7859a083bdb4a9c380f546e5f8407525/src/api.js#L17-L49 and also remembering that when using travis-ci.org, two builds would get triggered on a PR - and joining the dots and suspecting that the reason for this is also that a push to a PR results in both events getting fired.

CC @djmitche @imbstack @owlishDeveloper

**Comment by djmitche** [comment]
Fixed in #100.
